testname: Tokenizer Reconstruction MUSHRA 평가 (Add5)
testId: lmspt-eng-add5
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: generic
  id: welcome
  name: Welcome
  content: |
    <p>본 실험에 참여해 주셔서 감사합니다.</p>
    <ul>
      <li><strong>Reference</strong>: 100점의 기준이 되는 GT(원본) 음성입니다.</li>
      <li>문항당 <strong>6개</strong>의 음성에 대해 Reference를 기준으로 품질을 평가해 주세요.</li>
      <li>6개의 음성 중 하나는 Reference와 동일한 GT(원본) 음성입니다.</li>
      <li>Reference와 동일하다고 판단되는 음성에는 100점을 부여해 주세요.</li>
      <li>1~100점 척도로 <strong>음성의 품질</strong>만 평가해 주세요.</li>
    </ul>
    <p>아래 "Next" 버튼을 클릭하여 시작하세요.</p>
- type: mushra
  id: item_1
  name: 문항 1
  content: 5개 조건에 대해, 음성의 품질만 1~100점으로 평가해 주세요.
  showWaveform: true
  enableLooping: true
  reference: configs/resources/recon_eval_data/gt/DSGE2F5sTcg_00001.wav
  createAnchor35: false
  createAnchor70: false
  randomize: true
  showConditionNames: false
  stimuli:
    dualcodec: configs/resources/recon_eval_data/dualcodec/DSGE2F5sTcg_00001.wav
    lmspt-dc: configs/resources/recon_eval_data/lmspt-dc/DSGE2F5sTcg_00001.wav
    lmspt-mimi: configs/resources/recon_eval_data/lmspt-mimi/DSGE2F5sTcg_00001.wav
    mimi: configs/resources/recon_eval_data/mimi/DSGE2F5sTcg_00001.wav
- type: mushra
  id: item_2
  name: 문항 2
  content: 5개 조건에 대해, 음성의 품질만 1~100점으로 평가해 주세요.
  showWaveform: true
  enableLooping: true
  reference: configs/resources/recon_eval_data/gt/thghCiJZYwI_00009.wav
  createAnchor35: false
  createAnchor70: false
  randomize: true
  showConditionNames: false
  stimuli:
    dualcodec: configs/resources/recon_eval_data/dualcodec/thghCiJZYwI_00009.wav
    lmspt-dc: configs/resources/recon_eval_data/lmspt-dc/thghCiJZYwI_00009.wav
    lmspt-mimi: configs/resources/recon_eval_data/lmspt-mimi/thghCiJZYwI_00009.wav
    mimi: configs/resources/recon_eval_data/mimi/thghCiJZYwI_00009.wav
- type: mushra
  id: item_3
  name: 문항 3
  content: 5개 조건에 대해, 음성의 품질만 1~100점으로 평가해 주세요.
  showWaveform: true
  enableLooping: true
  reference: configs/resources/recon_eval_data/gt/E50E5hbggyM_00006.wav
  createAnchor35: false
  createAnchor70: false
  randomize: true
  showConditionNames: false
  stimuli:
    dualcodec: configs/resources/recon_eval_data/dualcodec/E50E5hbggyM_00006.wav
    lmspt-dc: configs/resources/recon_eval_data/lmspt-dc/E50E5hbggyM_00006.wav
    lmspt-mimi: configs/resources/recon_eval_data/lmspt-mimi/E50E5hbggyM_00006.wav
    mimi: configs/resources/recon_eval_data/mimi/E50E5hbggyM_00006.wav
- type: mushra
  id: item_4
  name: 문항 4
  content: 5개 조건에 대해, 음성의 품질만 1~100점으로 평가해 주세요.
  showWaveform: true
  enableLooping: true
  reference: configs/resources/recon_eval_data/gt/gegIAYxfpVA_00007.wav
  createAnchor35: false
  createAnchor70: false
  randomize: true
  showConditionNames: false
  stimuli:
    dualcodec: configs/resources/recon_eval_data/dualcodec/gegIAYxfpVA_00007.wav
    lmspt-dc: configs/resources/recon_eval_data/lmspt-dc/gegIAYxfpVA_00007.wav
    lmspt-mimi: configs/resources/recon_eval_data/lmspt-mimi/gegIAYxfpVA_00007.wav
    mimi: configs/resources/recon_eval_data/mimi/gegIAYxfpVA_00007.wav
- type: mushra
  id: item_5
  name: 문항 5
  content: 5개 조건에 대해, 음성의 품질만 1~100점으로 평가해 주세요.
  showWaveform: true
  enableLooping: true
  reference: configs/resources/recon_eval_data/gt/ravdess_sad-spk_01-intensity_01-statement_02-repetition_01.wav
  createAnchor35: false
  createAnchor70: false
  randomize: true
  showConditionNames: false
  stimuli:
    dualcodec: configs/resources/recon_eval_data/dualcodec/ravdess_sad-spk_01-intensity_01-statement_02-repetition_01.wav
    lmspt-dc: configs/resources/recon_eval_data/lmspt-dc/ravdess_sad-spk_01-intensity_01-statement_02-repetition_01.wav
    lmspt-mimi: configs/resources/recon_eval_data/lmspt-mimi/ravdess_sad-spk_01-intensity_01-statement_02-repetition_01.wav
    mimi: configs/resources/recon_eval_data/mimi/ravdess_sad-spk_01-intensity_01-statement_02-repetition_01.wav
- type: finish
  name: 평가 완료
  content: '<h2>평가해주셔서 감사합니다!</h2>

    <p>아래 정보를 입력한 후 제출해주세요.</p>

    '
  showResults: false
  writeResults: true
  questionnaire:
  - type: text
    label: 이름
    name: name
    optional: false
